AstroWorld/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AstroWorld.Areas.Admin.Models;
using AstroWorld.Areas.Admin.Models.Category;
using Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using UnitOfWork.Abstract;

namespace AstroWorld.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Admin")]
    public class CategoryController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }

        // GET: Category
        public ActionResult Index()
        {
            var viewModel = new GetCategoriesViewModel()
            {
                Categories = _unitOfWork.CategoryRepository.GetAll().ToList()
            };

            return View(viewModel);
        }

        // GET: Category/Details/5
        public ActionResult Details(int id)
        {
            var category = _unitOfWork.CategoryRepository.Get(x => x.Id == id);
            if (category==null)
            {
                return NotFound();
            }

            var viewModel = new CategoryDetailsViewModel()
            {
                CategoryId = category.Id,
                CreatedAt = category.CreatedAt,
                Description =  category.Description,
                Name= category.Name
               
            };


            return View(viewModel);
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateCategoryViewModel viewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(viewModel);
                }

                var newCategory = new Category()
                {
                    Name = viewModel.Name,
                    Description = viewModel.Description
                };

                _unitOfWork.CategoryRepository.Add(newCategory);
                if (_unitOfWork.Complete() > 0)
                {
                    return RedirectToAction(nameof(Index));
                }

                return View(viewModel);
            }
            catch
            {
                return View(viewModel);
            }
        }

        // GET: Category/Edit/5
        public ActionResult Edit(int id)
        {
            var category = _unitOfWork.CategoryRepository.Get(x => x.Id == id);
            if (category ==null)
            {
                return NotFound();
            }
                var viewModel = new UpdateCategoryViewModel()
                {
                    CategoryId = category.Id,
                    Description = category.Description,
                    Name = category.Name
                };
                return View(viewModel);
        }

        // POST: Category/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UpdateCategoryViewModel viewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(viewModel);
                }


                var toBeUpdaetdCategory = _unitOfWork.CategoryRepository.Get(x => x.Id == viewModel.CategoryId);
                toBeUpdaetdCategory.Name = viewModel.Name;
                toBeUpdaetdCategory.Description = viewModel.Description;
                _unitOfWork.CategoryRepository.Update(toBeUpdaetdCategory);
                if (_unitOfWork.Complete()>0)
                {
                    return RedirectToAction(nameof(Index));
                }

                return View(viewModel);
            }
            catch
            {
                return View(viewModel);
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                var category = _unitOfWork.CategoryRepository.Get(x => x.Id == id);
                if (category !=null)
                {
                    _unitOfWork.CategoryRepository.Remove(category);
                    if (_unitOfWork.Complete()>0)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                return NotFound();
            }
            catch (Exception)
            {

                return View();
            }


            
        }

        
    }
}

AstroWorld/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AstroWorld.Models.Book;
using AstroWorld.Models.WishList;
using Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UnitOfWork.Abstract;

namespace AstroWorld.Controllers
{
    public class BookController : Controller
    {
        private IUnitOfWork UnitOfWork;

        private SignInManager<ApplicationUser> SignInManager;

        private UserManager<ApplicationUser> UserManager;

        public BookController(IUnitOfWork unitOfWork,SignInManager<ApplicationUser> signInManager,UserManager<ApplicationUser> userManager)
        {
            UnitOfWork = unitOfWork;
            SignInManager = signInManager;
            UserManager = userManager;
        }

        public ActionResult Index()
        {
            
            var viewModel = new GetBooksViewModel()
            {
                Books = UnitOfWork.BookRepository.GetAll()
                .Where(z=>z.Draft==false)
                .Include(x=>x.User)
                .Include(y=>y.Category)
                .OrderByDescending(v => v.CreatedAt)
                .ToList()
                
            };

            return View(viewModel);
        }


        private bool isAdded(int bookid)
        {
            if (GetUserId()==null)
            {
                return true;
            }
            return  UnitOfWork.WishListRepository
                .GetWishLists(x => x.UserId == GetUserId() && x.BookId == bookid).FirstOrDefault() == null ? false : true;
        }

        
        public ActionResult Details(int id)
        {
            var book = UnitOfWork.BookRepository.Find(x=>x.Id == id).Include(y=>y.User).Include(z=>z.Category).FirstOrDefault();

            if (book == null)
            {
                return NotFound();
            }

            

            var viewModel = new DetailsBookViewModel()
            {
                BookId = book.Id,
                Name = book.Name,
                Description = book.Description,
                Author = book.Author,
                CreatedAt = book.CreatedAt,
                Draft = book.Draft,
                PhotoPath = book.PhotoPath,
                ReleaseYear = book.ReleaseYear,
                User = book.User,
                Category = book.Category,
                IsAdded=isAdded(id)


            };


            return View(viewModel);



        }

        [Authorize]
        public ActionResult Create()
        {
            var viewModel = new CreateBookViewModel()
            {
                CategoriesList = UnitOfWork.CategoryRepository.GetAll()
                .Select(x=>new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }).ToList()
            };

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult GetBookByCategory(int id)
        {

            var viewModel = new GetBooksViewModel()
            {
                Books = UnitOfWork.BookRepository.GetByCategoryId(id)
                .Where(x=>x.Draft==false)
                .Include(y=>y.User)
                .Include(z=>z.Category)
                .OrderByDescending(v=>v.CreatedAt)
                .ToList()
            };

            return View("Index",viewModel);
        }

        private string GetUserId()
        {
            if (SignInManager.IsSignedIn(User))
            {
                return User.FindFirst(ClaimTypes.NameIdentifier).Value;

            }
            else
            {
                return null;

            }
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateBookViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                var category = UnitOfWork.CategoryRepository.Get(x => x.Id == model.CategoryId);
                var user = await UserManager.FindByIdAsync(GetUserId());
                var newBook = new Book()
                {
                    Name = model.Name,
                    Description = model.Description,
                    Author = model.Author,
                    ReleaseYear = model.ReleaseYear,
                    Draft = model.Draft,
                    Category = category,
                    User = user
                    
                };

                UnitOfWork.BookRepository.Add(newBook);
                if (UnitOfWork.Complete()>0)
                {
                return RedirectToAction(nameof(Index));

                }
                return View(model);
            }
            catch
            {
                return View(model);
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult Edit(int id)
        {

            var book = UnitOfWork.BookRepository.Find(x => x.Id == id).Include(y => y.User).Include(z => z.Category).FirstOrDefault();

            if (book == null)
            {
                return NotFound();
            }
            if (book.User.Id != GetUserId())
            {
                return Forbid();
            }
            var viewModel = new UpdateBookViewModel()
            {
                BookId = book.Id,
                Name = book.Name,
                Description = book.Description,
                Draft = book.Draft,
                Author = book.Author,
                ReleaseYear = book.ReleaseYear,
                CategoryId = book.Category.Id,
                UserId = book.User.Id,
                CategoriesList = UnitOfWork.CategoryRepository.GetAll().Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }).ToList()
            };



            return View(viewModel);
        }

        
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UpdateBookViewModel viewModel)
        {
            try
            {
                var book = UnitOfWork.BookRepository.Find(x => x.Id == viewModel.BookId).Include(y => y.User).Include(v => v.Category).FirstOrDefault();

                if (book == null)
                {
                    return NotFound();
                }
                if (book.User.Id != GetUserId())
                {
                    return Forbid();
                }
                var category = UnitOfWork.CategoryRepository.Get(x => x.Id == viewModel.CategoryId);
                if (!ModelState.IsValid)
                {
                    return View(viewModel);
                }

                book.Name = viewModel.Name;
                book.Description = viewModel.Description;
                book.Author = viewModel.Author;
                book.ReleaseYear = viewModel.ReleaseYear;
                book.Draft = viewModel.Draft;
                book.Category = category;
                UnitOfWork.BookRepository.Update(book);
                if (UnitOfWork.Complete() > 0)
                {
                    return RedirectToAction(nameof(Details), new {id = book.Id } );

                }
                return View(viewModel);
            }
            catch
            {
                return View(viewModel);
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult Delete(int id)
        {
            var book = UnitOfWork.BookRepository.Find(x => x.Id == id).Include(y => y.User).Include(v => v.Category).FirstOrDefault();

            if (book == null)
            {
                return NotFound();
            }

            if (book.User.Id != GetUserId())
            {
                return Forbid();
            }

            UnitOfWork.BookRepository.Remove(book);
            if (UnitOfWork.Complete()>0)
            {
                return RedirectToAction(nameof(Index));
            }


            return View();
        }

        [HttpGet]
        public ActionResult GetBookByUser(string id)
        {
            
            var viewModel = new GetBooksViewModel()
            {
                Books = UnitOfWork.BookRepository.GetByUserId(id)
                .Where(x => x.Draft == false)
                .Include(y => y.User)
                .Include(z => z.Category)
                .OrderByDescending(v => v.CreatedAt)
                .ToList()
            };

            return View("Index", viewModel);
        }

        [HttpGet]
        [Authorize]
        public ActionResult GetBookByCuurentUser()
        {
            var viewModel = new GetBooksViewModel()
            {
                Books = UnitOfWork.BookRepository.Find(x=>x.User.Id == GetUserId())
                .Include(y => y.User)
                .Include(z => z.Category)
                .OrderByDescending(v => v.CreatedAt)
                .ToList()
            };

            return View("Index", viewModel);
        }

        
        [Authorize]
        [HttpPost]
        public async Task<ActionResult> AddToWishList(int bookId)
        {
            if (isAdded(bookId)==true)
            {
                return NoContent();
            }

            var book = UnitOfWork.BookRepository.Get(x => x.Id == bookId);
            if (book == null)
            {
                return NotFound();
            }

            if (book.Draft==true)
            {
                return NoContent();
            }
            var user = await UserManager.FindByIdAsync(GetUserId());

            var wishlist = new WishList()
            {
                Book = book,
                User = user
            };

AstroWorld/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using Entities;
@inject SignInManager<ApplicationUser> signInManager; 

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AstroWorld</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">AstroWorld</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>



                @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Manage
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Identity" asp-action="AllRoles">Roles</a>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Identity" asp-action="AllUsers">Users</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Book" asp-action="Index">Books</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-controller="Book" asp-action="GetBookByCuurentUser">MyBooks</a>
                            <a class="dropdown-item" asp-controller="Book" asp-action="GetWishlistOfCurrentUser">WishList</a>
                            <a class="dropdown-item" asp-controller="Book" asp-action="Create">Add new book</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Account" asp-action="Logout">
                            Logout @User.Identity.Name
                        </a>
                    </li>
                }

                else if (signInManager.IsSignedIn(User))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Manage
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-controller="Book" asp-action="GetBookByCuurentUser">MyBooks</a>

                            <a class="dropdown-item" asp-controller="Book" asp-action="GetWishlistOfCurrentUser">WishList</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-controller="Book" asp-action="Create">Add new book</a>
                        </div>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Account" asp-action="Logout">
                            Logout @User.Identity.Name
                        </a>
                    </li>

                }

                else
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
                    </li>
                }







            </ul>
            <!-- <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form> -->
        </div>
    </nav>








    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - AstroWorld - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>