AstroWorld/Areas/Admin/Models/Book/BookCreateViewModel.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AstroWorld.Areas.Admin.Models.Book
{
    public class BookCreateViewModel
    {
        
        [Required]
        [MaxLength(70)]
        public string Name { get; set; }

        [Required]
        [MaxLength(2000)]
        public string Description { get; set; }


        [Required]
        [MaxLength(80)]
        public string Author { get; set; }

        [Required]
        public DateTime ReleaseYear { get; set; }

        [Required]
        public bool Draft { get; set; }

        [Required]
        public string UserId { get; set; }
        [Required]
        public int CategoryId { get; set; }
        public List<SelectListItem> UsersList { get; set; }

        public IFormFile PhotoPath { get; set; }

        public List<SelectListItem> CategoriesList { get; set; }
    }
}

AstroWorld/Areas/Admin/Models/Book/BookDeleteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AstroWorld.Areas.Admin.Models.Book
{
    public class BookDeleteViewModel
    {
        public int BookId { get; set; }

        public string Name { get; set; }

        public string UserId { get; set; }

    }
}

AstroWorld/Areas/Admin/Models/Book/BookDetailsViewModel.cs
using Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AstroWorld.Areas.Admin.Models.Book
{
    public class BookDetailsViewModel
    {

        public int BookId { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string Author { get; set; }

        public DateTime ReleaseYear { get; set; }

        public bool Draft { get; set; }

        public ApplicationUser  User { get; set; }
        public Entities.Category Category { get; set; }

        public string PhotoPath { get; set; }

        public DateTime CreatedAt { get; set; }


    }
}

AstroWorld/Areas/Admin/Models/Book/BookUpdateViewModel.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AstroWorld.Areas.Admin.Models.Book
{
    public class BookUpdateViewModel
    {
        public int BookId { get; set; }

        public string Name { get; set; }

       
        public string Description { get; set; }


        public string Author { get; set; }

        
        public DateTime ReleaseYear { get; set; }

        
        public bool Draft { get; set; }

        public List<SelectListItem> UsersList { get; set; }

        public List<SelectListItem> CategoriesList { get; set; }

        public IFormFile PhotoPath { get; set; }


        [Required]
        public string UserId { get; set; }
        [Required]
        public int CategoryId { get; set; }
    }
}

AstroWorld/Areas/Admin/Models/Book/GetAllBooksViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AstroWorld.Areas.Admin.Models.Book
{
    public class GetAllBooksViewModel
    {
        public List<Entities.Book> Books { get; set; }

    }
}

AstroWorld/Models/Book/CreateBookViewModel.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AstroWorld.Models.Book
{
    public class CreateBookViewModel
    {
        [Required]
        [MaxLength(70)]
        public string Name { get; set; }

        [Required]
        [MaxLength(2000)]
        public string Description { get; set; }


        [Required]
        [MaxLength(80)]
        public string Author { get; set; }

        [Required]
        public DateTime ReleaseYear { get; set; }

        [Required]
        public bool Draft { get; set; }

        
        [Required]
        public int CategoryId { get; set; }
        
        public IFormFile PhotoPath { get; set; }

        public List<SelectListItem> CategoriesList { get; set; }
    }
}

AstroWorld/Models/Book/DetailsBookViewModel.cs
using Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AstroWorld.Models.Book
{
    public class DetailsBookViewModel
    {

        public int BookId { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string Author { get; set; }

        public DateTime ReleaseYear { get; set; }

        public bool Draft { get; set; }

        public ApplicationUser User { get; set; }
        public Entities.Category Category { get; set; }

        public string PhotoPath { get; set; }

        public DateTime CreatedAt { get; set; }
        public bool IsAdded { get; internal set; }
    }
}

AstroWorld/Models/Book/GetBooksViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AstroWorld.Models.Book
{
    public class GetBooksViewModel
    {
        public List<Entities.Book> Books { get; set; }
    }
}

AstroWorld/Models/Book/UpdateBookViewModel.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AstroWorld.Models.Book
{
    public class UpdateBookViewModel
    {

        public int BookId { get; set; }

        public string Name { get; set; }


        public string Description { get; set; }


        public string Author { get; set; }


        public DateTime ReleaseYear { get; set; }


        public bool Draft { get; set; }

        public List<SelectListItem> CategoriesList { get; set; }

        public IFormFile PhotoPath { get; set; }
        [Required]
        public string UserId { get; set; }


        [Required]
        public int CategoryId { get; set; }


    }
}

AstroWorld/Areas/Admin/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AstroWorld.Areas.Admin.Models.Book;
using Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UnitOfWork.Abstract;

namespace AstroWorld.Areas.Admin.Controllers
{   
    [Area("Admin")]
    [Authorize(Roles ="Admin")]
    public class BookController : Controller
    {
        private IUnitOfWork _unitOfWork;

        private UserManager<ApplicationUser> UserManager; 

        public BookController(IUnitOfWork unitOfWork , UserManager<ApplicationUser> userManager)
        {
            this._unitOfWork = unitOfWork;
            UserManager = userManager;
        }

       
        public ActionResult Index()
        {
            var viewModel = new GetAllBooksViewModel()
            {
                Books = _unitOfWork.BookRepository.GetAll().Include(x => x.User).ToList()
            };

            return View(viewModel);
        }

        
        public ActionResult Details(int id)
        {
            var book = _unitOfWork.BookRepository.Get(x => x.Id == id);
            
            if (book==null)
            {
                return NotFound(); 
            }

            var viewModel = new BookDetailsViewModel()
            {
                BookId = book.Id,
                Name = book.Name,
                Description = book.Description,
                Author = book.Author,
                CreatedAt = book.CreatedAt,
                Draft = book.Draft,
                PhotoPath = book.PhotoPath,
                ReleaseYear = book.ReleaseYear,
                User  = book.User,
                Category = book.Category


            };


            return View(viewModel);
        }

       
        public ActionResult Create()
        {

            var model = new BookCreateViewModel()
            {

                CategoriesList = _unitOfWork.CategoryRepository.GetAll().
                                        Select(x => new SelectListItem
                                        {
                                            Text=x.Name,
                                            Value = x.Id.ToString()
                                        }).ToList(),
                UsersList  = UserManager.Users.ToList()
                                    .Select(y=>new SelectListItem
                                    {
                                        Text=y.Email,
                                        Value = y.Id
                                    }).ToList()
              

            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(BookCreateViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                var user = await UserManager.FindByIdAsync(model.UserId);
                var category = _unitOfWork.CategoryRepository.Get(x => x.Id == model.CategoryId);
                var newBook = new Book()
                {
                    Name = model.Name,
                    ReleaseYear =model.ReleaseYear,
                    Author = model.Author,
                    Description = model.Description,
                    Draft = model.Draft,
                    User = user,
                    Category = category
                    
                };

                 _unitOfWork.BookRepository.Add(newBook);
                if (_unitOfWork.Complete() > 0)
                {
                    return RedirectToAction(nameof(Index));
                }

                return View(model);
            }
            catch
            {
                return View(model);
            }
        }

       
        public ActionResult Edit(int id)
        {
            var book = _unitOfWork.BookRepository.Find(x => x.Id == id).Include(y=>y.User).Include(v=>v.Category).FirstOrDefault();
            
            if (book==null)
            {
                return NotFound();
            }

            var viewModel = new BookUpdateViewModel()
            {
                BookId = book.Id,
                Name = book.Name,
                Description = book.Description,
                Author = book.Author,
                Draft = book.Draft,
                UserId  = book.User.Id,
                ReleaseYear = book.ReleaseYear,
                CategoryId = book.Category.Id,
                CategoriesList = _unitOfWork.CategoryRepository.GetAll().
                                        Select(x => new SelectListItem
                                        {
                                            Text=x.Name,
                                            Value = x.Id.ToString()
                                        }).ToList(),
                UsersList  = UserManager.Users.ToList()
                                    .Select(y=>new SelectListItem
                                    {
                                        Text=y.Email,
                                        Value = y.Id
                                    }).ToList()
            };

            return View(viewModel);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(BookUpdateViewModel viewModel)
        {
            try
            {
                var book = _unitOfWork.BookRepository.Find(x => x.Id == viewModel.BookId).Include(y => y.User).Include(v => v.Category).FirstOrDefault();

                if (book == null)
                {
                    return NotFound();
                }

                var user = await UserManager.FindByIdAsync(viewModel.UserId);
                var category = _unitOfWork.CategoryRepository.Get(x => x.Id == viewModel.CategoryId);
                if (!ModelState.IsValid)
                {
                    return View(viewModel);
                }

                book.Name = viewModel.Name;
                book.Description = viewModel.Description;
                book.Author = viewModel.Author;
                book.ReleaseYear = viewModel.ReleaseYear;
                book.Draft = viewModel.Draft;
                book.User = user;
                book.Category = category;
                _unitOfWork.BookRepository.Update(book);

                if (_unitOfWork.Complete() > 0)
                {
                return RedirectToAction(nameof(Index));
                   
                }
                return View(viewModel);
            }
            catch
            {
                return View(viewModel);
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {

            var book = _unitOfWork.BookRepository.Get(x => x.Id == id);
            if (book==null)
            {
                return NotFound();
            }

            _unitOfWork.BookRepository.Remove(book);

            if (_unitOfWork.Complete()>0)
            {
                return RedirectToAction(nameof(Index));
            }
            return  RedirectToAction(nameof(Index));

        }

        
       
    }
}

AstroWorld/ViewComponents/CategoryListViewComponent.cs
using AstroWorld.Models.Category;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UnitOfWork.Abstract;

namespace AstroWorld.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {
        private IUnitOfWork UnitOfWork;
        public CategoryListViewComponent(IUnitOfWork unitOfWork)
        {
            UnitOfWork = unitOfWork;
        }
        public ViewViewComponentResult Invoke()
        {

            var model = new CategoryListViewModel()
            {
                Categories = UnitOfWork.CategoryRepository.GetAll().ToList()
            };

            return View(model);
        }


    }
}

AstroWorld/ViewComponents/LastAddedBooksViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UnitOfWork.Abstract;

namespace AstroWorld.ViewComponents
{
    public class LastAddedBooksViewComponent:ViewComponent
    {
        private  IUnitOfWork unitOfWork;

        public LastAddedBooksViewComponent(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public ViewViewComponentResult Invoke()
        {
            List<Entities.Book> lastAdded2 = unitOfWork.BookRepository.GetLatestBooks(2)
                .ToList();
                

            return View(lastAdded2);
        }

    }
}

AstroWorld/ViewComponents/RandomPostViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UnitOfWork.Abstract;

namespace AstroWorld.ViewComponents
{
    public class RandomPostViewComponent : ViewComponent
    {
        private IUnitOfWork UnitOfWork;
        public RandomPostViewComponent(IUnitOfWork unitOfWork)
        {
            UnitOfWork = unitOfWork;
        }
        public ViewViewComponentResult Invoke()
        {
            return View(UnitOfWork.BookRepository.GetRandomBook().FirstOrDefault());
        }
    }
}

AstroWorld/Views/Book/Create.cshtml
@model CreateBookViewModel
@{
    ViewData["Title"] = "Create";
}

<br />
<br />
<div class="row">



    <div class="col-4">
        <h3 class="m-3">
            Create Book
        </h3>

        <form method="Post">

            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-group ">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseYear"></label>
                <input asp-for="ReleaseYear" class="form-control" />
                <span asp-validation-for="ReleaseYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId"></label>
                <select asp-for="CategoryId" asp-items="@Model.CategoriesList" class="form-control">
                    <option>
                        Select a category
                    </option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>
                    Draft?
                    <input type="checkbox" style="width:15px" asp-for="Draft" class="form-control" />
                </label>

                <span asp-validation-for="Draft" class="text-danger"></span>
            </div>





            <div class="form-group">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    <a class="ml-2" asp-action="Index" asp-controller="Book">Back To List</a>
                </small>
            </div>

        </form>
    </div>
    <div class="col-4">

    </div>
</div>

AstroWorld/Views/Book/Details.cshtml
@model DetailsBookViewModel

@inject SignInManager<ApplicationUser> signInManager;
@{
    ViewData["Title"] = "Details";
}

<br />

<div class="row" >

    <div class="col-md-7">
        <div class="jumbotron">

    <a asp-controller="Book" asp-action="GetBookByUser" asp-route-id="@Model.User.Id" class="mr-1">@Model.User.UserName</a>
    <br>
    <small class="text-muted">Created At : @Model.CreatedAt </small>
    <h1 class="display-4"> @Model.Name</h1>
    <p>Author :  @Model.Author</p>
    <p>
        @Model.Description
    </p>
    <p>
        Release Year :@Model.ReleaseYear.Year
    </p>
    <hr class="my-2">
    <p>Category : <a asp-controller="Book" asp-action="GetBookByCategory" asp-route-id="@Model.Category.Id" class="mr-1">  @Model.Category.Name</a></p>

    @if (Model.Draft == true)
    {
        <p>This has not been published yet!</p>
    }

    @if (signInManager.IsSignedIn(User))
    {
        if (Model.User.UserName == User.Identity.Name)
        {
            <form asp-controller="Book" asp-action="Delete" asp-route-id="@Model.BookId" method="post">
                <a asp-controller="Book" asp-action="Edit" asp-route-id="@Model.BookId" class="btn btn-sm btn-primary">Edit</a> |
                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this category: @Model.Name')">Delete</button>
            </form>
        }
        <br>
        <form asp-controller="Book" method="post">

            @if (!Model.Draft)
            {
                @if (Model.IsAdded)
                {
                    <button type="submit" asp-action="RemoveFromWishList" asp-route-bookId="@Model.BookId" class="btn btn-success btn-sm">Remove from WishList</button>
                }
                else
                {
                    <button type="submit" asp-action="AddToWishList" asp-route-bookId="@Model.BookId" class="btn btn-success btn-sm">Add to Watch List</button>

                }
            }


        </form>

    }





    <hr />

</div>
    </div>
    <div class="col-md-3">
        @await Component.InvokeAsync("LastAddedBooks")
    </div>


</div>

AstroWorld/Views/Book/Edit.cshtml
@model UpdateBookViewModel
@{
    ViewData["Title"] = "Edit";
}






<div class="row">



    <div class="col-4">
        <h3 class="m-3">
            Edit Book
        </h3>

        <form method="Post">

            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="BookId" />
            <input type="hidden" asp-for="UserId" />
            <div class="form-group ">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Author"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ReleaseYear"></label>
                <input asp-for="ReleaseYear" class="form-control" />
                <span asp-validation-for="ReleaseYear" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CategoryId"></label>
                <select asp-for="CategoryId" asp-items="@Model.CategoriesList" class="form-control">
                    <option>
                        Select a category
                    </option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>
                    Draft?
                    <input type="checkbox" style="width:15px" asp-for="Draft" class="form-control" />
                </label>

                <span asp-validation-for="Draft" class="text-danger"></span>
            </div>





            <div class="form-group">
                <button type="submit" class="btn btn-primary">Edit</button>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    <a class="ml-2" asp-action="Index" asp-controller="Book" asp-route-id="@Model.BookId">Back To List</a>
                </small>
            </div>

        </form>
    </div>
    <div class="col-4">

    </div>
</div>

AstroWorld/Views/Book/GetWishlistOfCurrentUser.cshtml
@model GetWishlistViewModel
@{
    ViewData["Title"] = "GetWishlistOfCurrentUser";
}


<br />
<div class="row">
    <div class="col-md-2">

        


    </div>



    <div class="col-md-7">


        @foreach (var item in Model.WishLists)
        {

            <div class="jumbotron">

                <a asp-controller="Book" asp-action="GetBookByUser" asp-route-id="@item.User.Id" class="mr-1">@item.User.UserName</a>
                <br>
                <small class="text-muted">Created At : @item.Book.CreatedAt </small>
                <h1 class="display-4"> @item.Book.Name</h1>
                <p>Author :  @item.Book.Author</p>

                <hr class="my-2">
                <p>Category : <a asp-controller="Book" asp-action="GetBookByCategory" asp-route-id="@item.Book.Category.Id" class="mr-1">  @item.Book.Category.Name</a></p>

                <a class="btn btn-primary btn-sm" asp-controller="Book" asp-action="Details" asp-route-id="@item.Book.Id" role="button">Learn more</a>
               
            </div>

        }
    </div>



    <div class="col-md-3"></div>
</div>

AstroWorld/Views/Book/Index.cshtml
@model GetBooksViewModel
@{
    ViewData["Title"] = "Index";
}

<br />
<br />
    <div class="row">
        <div class="col-md-2">

            @await Component.InvokeAsync("CategoryList") 


        </div>

        
        
        <div class="col-md-7">

            @if (Model.Books.Any())
            {
                @foreach (var item in Model.Books)
                {

                    <div class="jumbotron">

                        <a asp-controller="Book" asp-action="GetBookByUser" asp-route-id="@item.User.Id" class="mr-1">@item.User.UserName</a>
                        <br>
                        <small class="text-muted">Created At : @item.CreatedAt </small>
                        <h1 class="display-4"> @item.Name</h1>
                        <p>Author :  @item.Author</p>

                        <hr class="my-2">
                        
                        <p>Category : <a asp-controller="Book" asp-action="GetBookByCategory" asp-route-id="@item.Category.Id" class="mr-1">  @item.Category.Name</a></p>
                        @if (item.Draft==true)
	                     {
                        <p class="alert alert-info">This has not been published yet!</p>
		 
	                     }
                        <a class="btn btn-primary btn-sm" asp-controller="Book" asp-action="Details" asp-route-id="@item.Id" role="button">Learn more</a>

                    </div>

                }
            }
            else
            {

                <a asp-controller="Book" asp-action="Create" class="btn btn-outline-success" >Create New Book</a>
            }




        </div>
        
        
        
        <div class="col-md-3">

            @await Component.InvokeAsync("RandomPost")

        </div>
    </div>